POST http://localhost:9000/api/v1/admin/users
Content-Type: application/json

{
  "username" : "spring",
  "password" :  "1234",
  "email" : "spring@woorinpang.com",
  "name" : "baekho",
  "roleCode" : "ROLE_USER",
  "userStateCode" :  "NORMAL"
}