### 회원가입
POST {{host}}/users/join
Content-Type: application/json

{
  "username" : "spring",
  "password" : "Dlgmlcjf1!",
  "email" : "spring@woorinpang.com",
  "name" : "baekho"
}

### 로그인
POST {{host}}/login
Content-Type: application/json

{
  "username" : "spring",
  "password" : "Dlgmlcjf1!"
}