spring.application.name: user-service

spring:
  config:
    import:
      - optional:configserver:http://localhost:8888
      - core-storage.yml
  mvc.throw-exception-if-no-handler-found: true
  web.resources.add-mappings: false

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100
  port: 0

---
spring.config.activate.on-profile: local


---
spring.config.activate.on-profile: dev


---
spring.config.activate.on-profile: prod