server:
  port: 8080 # random port

spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL570Dialect
#        storage_engine: innodb
        format_sql: true
        default_batch_fetch_size: 1000
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
    show-sql: true
  cache:
    jcache:
      config: classpath:ehcache.xml

# 2시간(7,200,000), 1일(86,400,000) jwt token
token:
  expiration_time: 7200000
  refresh_time: 86400000
  secret: 'token_secret'

file:
  directory: ${app.home:${user.home}}/workspace/github/woorinpang/msa-attach-volume #url 사용시에는 사용되지 않는다.
  url: http://${file.hostname:localhost}:8080 #nginx 로 파일 다운로드 처리
messages:
  directory: ${file.directory}/messages