### 아이디 중복 체크
POST {{host}}/auth/username/exists
Content-Type: application/json

{
  "email" : "spring"
}

### 회원가입
POST {{host}}/auth/join
Content-Type: application/json

{
  "email" : "spring@woorinpang.com",
  "password" : "Tmvmfld1!",
  "name" : "스프링"
}

### 로그인
POST {{host}}/login
Content-Type: application/json

{
  "email" : "spring@woorinpang.com",
  "password" : "Tmvmfld1!"
}

### 구글 로그인
POST {{host}}/login
Content-Type: application/json

{
  "email": "",
  "password": "",
  "token": "{{google_token}}",
  "provider" : "GOOGLE"
}

### 카카오 로그인
POST {{host}}/login
Content-Type: application/json

{
  "email": "",
  "password": "",
  "token": "{{kakao_token}}",
  "provider" : "KAKAO"
}

### 네이버 로그인
POST {{host}}/login
Content-Type: application/json

{
  "email": "",
  "password": "",
  "token": "{{naver_token}}",
  "provider" : "NAVER"
}