### 내 정보 조회
GET {{host}}/users/2
Authorization: {{access-token}}

### 내 정보 수정
PUT {{host}}/users/2
Content-Type: application/json
Authorization: {{access-token}}

{
  "name" : "스프링수정"
}

### 회원탈퇴
DELETE {{host}}/users/2
Authorization: {{access-token}}