### 내 정보 조회
GET {{host}}/users/17
Authorization: {{access_token}}

### 내 정보 수정
PUT {{host}}/users/16
Content-Type: application/json
Authorization: {{access_token}}

{
  "name" : "스프링수정"
}

### 회원탈퇴
DELETE {{host}}/users/16
Authorization: {{access_token}}