### 내 정보 조회
GET {{host}}/users/1
Authorization: {{access-token}}

### 내 정보 수정
PUT {{host}}/users/1
Content-Type: application/json
Authorization: {{access-token}}

{
  "email" : "spring@woorinpang.com",
  "name" : "스프링"
}

### 회원탈퇴
DELETE {{host}}/users/1
Authorization: {{access-token}}